import React from 'react'
import Head from 'next/head'
import { Carousel, Footer, Header, Navbar, ProductCard } from '../components'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Shop like abed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Navbar />
      <Carousel/>
      <div className="mx-28 my-20 ">
      <ProductCard />
      </div>
      <main >
       
      </main>
        <Footer />
    </div>
  )
}
